//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGENDA
    {
        public int COD_AGE { get; set; }
        public string NOME { get; set; }
        public string HORA { get; set; }
        public Nullable<int> COD_PROF { get; set; }
        public string COD_PRO { get; set; }
        public Nullable<System.DateTime> DATA { get; set; }
        public string STATUS { get; set; }
        public string EMITIUFAA { get; set; }
        public string NOMECAMP { get; set; }
        public Nullable<int> COD_DTRAB { get; set; }
        public Nullable<int> ATENDIMENTONUM { get; set; }
        public Nullable<int> NFAA { get; set; }
        public Nullable<int> COD_UNI { get; set; }
        public string CONSULTADO { get; set; }
        public Nullable<int> COD_LISTA_CR { get; set; }
        public string LOCAL { get; set; }
        public Nullable<bool> PRECONS { get; set; }
        public Nullable<bool> CANCELADAAUTO { get; set; }
        public Nullable<int> NFAO { get; set; }
        public Nullable<bool> BLOQUEADO { get; set; }
        public Nullable<int> COD_USU { get; set; }
        public Nullable<System.DateTime> DATA_AGENDAMENTO { get; set; }
        public Nullable<int> COD_USU_GEROUAG { get; set; }
        public Nullable<System.DateTime> DATA_GEROUAG { get; set; }
        public Nullable<System.DateTime> DATA_PEDIDO { get; set; }
        public string MOTIVO_BLOQUEIO { get; set; }
        public Nullable<System.DateTime> DATA_BLOQUEIO { get; set; }
        public Nullable<int> COD_USU_BLOQUEIO { get; set; }
        public Nullable<bool> URGENCIA { get; set; }
        public string TIPO_CONSULTA { get; set; }
        public Nullable<int> COD_PROF_REQ { get; set; }
        public Nullable<int> COD_UNI_REQ { get; set; }
        public Nullable<bool> CONFIRMOU_AGE { get; set; }
        public Nullable<System.DateTime> DATA_CONFIRMOU { get; set; }
        public Nullable<System.DateTime> DATA_CANCELOU { get; set; }
        public Nullable<System.Guid> CODIGOQR { get; set; }
    }
}
