//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGENDAEXA
    {
        public int COD_AGE_EXA { get; set; }
        public string COD_PRO { get; set; }
        public Nullable<int> COD_PROF { get; set; }
        public string EXT_INT { get; set; }
        public Nullable<int> COD_EXA { get; set; }
        public Nullable<int> COD_LAB { get; set; }
        public Nullable<System.DateTime> DATA_COL { get; set; }
        public Nullable<int> COD_COL { get; set; }
        public Nullable<System.DateTime> DATA_EXA { get; set; }
        public Nullable<System.DateTime> DATA_CHE { get; set; }
        public Nullable<System.DateTime> DATA_RET { get; set; }
        public string STATUS { get; set; }
        public Nullable<int> Num { get; set; }
        public Nullable<int> COD_SUB_EXA { get; set; }
        public string HORA_EXA { get; set; }
        public Nullable<int> COD_PROCED { get; set; }
        public string NOME_EXAME { get; set; }
        public Nullable<float> VALOR { get; set; }
        public Nullable<System.DateTime> AGENDADATA { get; set; }
        public string OBSERVACOES { get; set; }
        public Nullable<System.DateTime> DATA_RESULTADO { get; set; }
        public string NOMEENTREGOU { get; set; }
        public Nullable<int> COD_USU { get; set; }
        public Nullable<bool> LAUDADO { get; set; }
        public Nullable<int> COD_UNI { get; set; }
        public Nullable<int> COD_UNISOLICITANTE { get; set; }
        public Nullable<bool> URGENCIA { get; set; }
        public Nullable<System.DateTime> DATA_ENTREGA { get; set; }
        public Nullable<int> COD_USUAGENDO { get; set; }
        public Nullable<int> COD_USUREALIZO { get; set; }
        public Nullable<int> COD_USUCANCELO { get; set; }
        public Nullable<int> COD_AMOSTRAEXA { get; set; }
        public string NOME_PAC { get; set; }
        public string SEXO_PAC { get; set; }
        public Nullable<System.DateTime> DTNASC_PAC { get; set; }
        public Nullable<bool> STATUS_DISPONIVEL { get; set; }
        public Nullable<int> COD_BPAITEN { get; set; }
        public Nullable<int> COD_EQUIPAMENTO { get; set; }
        public Nullable<int> COD_MATERIAL { get; set; }
        public Nullable<int> PROTOCOLO_AGE { get; set; }
        public Nullable<int> COD_AGENDAEXA_MASTER { get; set; }
        public string ENDERECO_RESULTADO { get; set; }
        public Nullable<int> COD_AGEEXA_COLETA { get; set; }
    }
}
