//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALUNOS
    {
        public int COD_ALUNO { get; set; }
        public Nullable<int> COD_CIDADAO { get; set; }
        public string ANO_ADMISSAO { get; set; }
        public string REGISTRO_MATRICULA { get; set; }
        public string REGISTRO_ALUNO { get; set; }
        public string DIGITO_CONTROLE_RA { get; set; }
        public string UF_RA { get; set; }
        public string NECES_EDUC_ESPECIAL { get; set; }
        public string TIPO_NECES_ESPECIAL { get; set; }
        public string BOLSA_FAMILIA { get; set; }
        public string MUNICIPIO_NASCIMENTO_ALUNO { get; set; }
        public string ESCOLA_PROCEDENCIA { get; set; }
        public string MUNICIPIO_PROCEDENCIA { get; set; }
        public string DISTRITO_PROCEDENCIA { get; set; }
        public string OBSERVACAO { get; set; }
        public Nullable<System.DateTime> DTALTERACAO { get; set; }
        public Nullable<int> USUARIO_ALT { get; set; }
        public Nullable<int> NGDAE { get; set; }
        public Nullable<int> COD_ESCOLA_PROCED { get; set; }
        public Nullable<int> COD_NECESSIDADE { get; set; }
        public Nullable<int> COD_CID_EST { get; set; }
        public Nullable<int> COD_UF_EST { get; set; }
    }
}
