//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALUNOS_APP
    {
        public int ID { get; set; }
        public Nullable<int> COD_ALUNO { get; set; }
        public Nullable<int> COD_CIDADAO { get; set; }
        public string NOME { get; set; }
        public string ANO_ADMISSAO { get; set; }
        public string REGISTRO_ALUNO { get; set; }
        public string DIGITO_CONTROLE_RA { get; set; }
        public string UF_RA { get; set; }
        public string ESCOLA_PROCEDENCIA { get; set; }
        public Nullable<System.Guid> CODIGO_QR_ALUNO { get; set; }
        public Nullable<System.Guid> CODIGO_QR { get; set; }
        public Nullable<System.DateTime> DATA_INSERT { get; set; }
        public Nullable<System.DateTime> DT_ULT_ATUALIZACAO { get; set; }
    }
}
