//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANEISMETALICOSVISUAL
    {
        public int Id { get; set; }
        public int FK_INSPECAOMATERIAL { get; set; }
        public string CORROCAO { get; set; }
        public string OXIDACAO { get; set; }
        public string SULCOS { get; set; }
    }
}
