//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARTEIRA_VACINA
    {
        public int COD_CARTEIRA_VACINA { get; set; }
        public string NUM_DOSE { get; set; }
        public int COD_VACI { get; set; }
        public int COD_CARTE { get; set; }
        public Nullable<int> COD_LOTE_VACI { get; set; }
        public Nullable<System.DateTime> DATA_APLICACAO { get; set; }
        public bool APLICADA { get; set; }
        public Nullable<int> COD_PROF_RECEIT { get; set; }
        public Nullable<int> COD_PROF { get; set; }
        public string NOME_PROF { get; set; }
        public string NOME_PROF_RECEIT { get; set; }
        public string RG_APLICOU { get; set; }
        public string COD_SAIDA_VACI { get; set; }
        public Nullable<int> COD_UNI { get; set; }
        public Nullable<int> COD_CAMP { get; set; }
        public Nullable<int> COD_MOT_VACI { get; set; }
        public Nullable<System.DateTime> DT_APLICACAO_V { get; set; }
        public string TIPO_DOSE { get; set; }
    }
}
