//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CEPBRASIL
    {
        public string CIDADE_ESTADO { get; set; }
        public string RUA_BAIRRO { get; set; }
        public string CEP { get; set; }
        public int ID { get; set; }
        public string BAIRRO { get; set; }
        public string ESTADO { get; set; }
    }
}
