//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIDADAO
    {
        public int COD_CIDADAO { get; set; }
        public string NOME { get; set; }
        public string SOBRENOME { get; set; }
        public string SEXO { get; set; }
        public string OCUPACAO { get; set; }
        public Nullable<int> COD_DOMICILIO { get; set; }
        public string COD_FAMILIA { get; set; }
        public string ENDERECO { get; set; }
        public string NUM { get; set; }
        public string COMPLEMENTO { get; set; }
        public string BAIRRO { get; set; }
        public string MUNICIPIO { get; set; }
        public string CEP { get; set; }
        public string ESTADO { get; set; }
        public string SIGLA { get; set; }
        public string AREA { get; set; }
        public string MICROAREA { get; set; }
        public string ZONA_RESIDENCIA { get; set; }
        public string PAI { get; set; }
        public string MAE { get; set; }
        public string CONJUGE { get; set; }
        public Nullable<System.DateTime> DTNASC { get; set; }
        public string ANO_PRIMEIRO_EMPREGO { get; set; }
        public string LOC_TRABALHO { get; set; }
        public string FONE_RESIDENCIAL { get; set; }
        public string FONE_CELULAR { get; set; }
        public string FONE_COMERCIAL { get; set; }
        public string FONE_CONTATO { get; set; }
        public string NUM_IDENTIFICACAO_SOCIAL { get; set; }
        public string CPF { get; set; }
        public string RG { get; set; }
        public string RG_COMP { get; set; }
        public string RG_UF { get; set; }
        public Nullable<System.DateTime> RG_EMISSAO { get; set; }
        public string PAIS_NASCIMENTO { get; set; }
        public string REGISTRO_NACIONAL_ESTRANGEIRO { get; set; }
        public string ANO_CHEGADA { get; set; }
        public Nullable<System.DateTime> DATA_ENTRADA_PAIS { get; set; }
        public string CERTIDAOMUNICIPIO { get; set; }
        public string CERTIDAODISTRITO { get; set; }
        public string CERTIDAOCARTORIO { get; set; }
        public string CERTIDAOLIVRO { get; set; }
        public string CERTIDAOFOLHA { get; set; }
        public string CERTIDAOTERMO { get; set; }
        public string CERTIDAONUMERO { get; set; }
        public Nullable<System.DateTime> CERTIDAOEMISSAO { get; set; }
        public string TITULONUM { get; set; }
        public string TITULOZONA { get; set; }
        public string TITULOSECAO { get; set; }
        public string CARTEIRAPNUM { get; set; }
        public string CARTEIRAPSERIE { get; set; }
        public string CARTEIRAPUF { get; set; }
        public Nullable<System.DateTime> CARTEIRAPEMI { get; set; }
        public string PISNUM { get; set; }
        public string RACACOR { get; set; }
        public string RELIGIAO { get; set; }
        public string NATURALIDADE { get; set; }
        public string ESCOLARIDADE { get; set; }
        public string ESTADO_CIVIL { get; set; }
        public string SUS { get; set; }
        public Nullable<bool> OBITO { get; set; }
        public Nullable<System.DateTime> DTOBITO { get; set; }
        public Nullable<bool> ATIVO { get; set; }
        public Nullable<System.DateTime> NASCCONJUGE { get; set; }
        public string DIGITAL { get; set; }
        public string EMAIL { get; set; }
        public string PAIS_ORIGEM { get; set; }
        public Nullable<System.DateTime> DTNATURALIZACAO { get; set; }
        public Nullable<System.DateTime> DTCHEGADA { get; set; }
        public string NPORTARIA { get; set; }
        public Nullable<int> RG_ORGEMI { get; set; }
        public string TIPO_CERTIDAO { get; set; }
        public string SITUACAO_CONJUGAL { get; set; }
        public string NACIONALIDADE { get; set; }
        public string ETNIA { get; set; }
        public string TIPOPESSOA { get; set; }
        public Nullable<bool> PRESIDIARIO { get; set; }
        public string APELIDO { get; set; }
        public Nullable<System.DateTime> DATA_INSERT { get; set; }
        public Nullable<System.DateTime> DT_ULT_ATUALIZACAO { get; set; }
        public Nullable<System.Guid> CODIGO_QR { get; set; }
    }
}
