//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONVERSACAO
    {
        public int ID { get; set; }
        public string DE { get; set; }
        public string PARA { get; set; }
        public Nullable<System.DateTime> DATA { get; set; }
        public string CONVERSA { get; set; }
    }
}
