//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DadosEtiquetasPedidoSet
    {
        public int Id { get; set; }
        public string Id_cliente { get; set; }
        public string Fornecedor { get; set; }
        public string CNPJ { get; set; }
        public string Numero_pedido { get; set; }
        public string Item { get; set; }
        public string Referencia { get; set; }
        public string Codigo_de_barras { get; set; }
        public string Preco { get; set; }
        public Nullable<int> Qtde_original { get; set; }
        public Nullable<int> Qtde_entregue { get; set; }
        public Nullable<int> Qtde_consumida { get; set; }
        public string Modelo_etiqueta { get; set; }
        public string Descricao_material { get; set; }
        public string Estrutura_mercadologica { get; set; }
        public string Email_do_fornecedor { get; set; }
        public string Email_do_representante { get; set; }
        public string Email_do_responsavel { get; set; }
        public string Baixado { get; set; }
        public Nullable<int> Posicao { get; set; }
        public string Status_pedido { get; set; }
        public string Urgente { get; set; }
        public Nullable<int> Saldo_qtde_pedido { get; set; }
        public string Data_entrega { get; set; }
        public string Mensagem_etiqueta { get; set; }
        public string Imprimindo { get; set; }
        public string Campanha { get; set; }
        public string Tema { get; set; }
        public string TipoCodBarra { get; set; }
    }
}
