//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXAME_PAC
    {
        public int ID { get; set; }
        public Nullable<int> COD_AGE_EXA { get; set; }
        public Nullable<System.DateTime> DATA_EXAME { get; set; }
        public string HORA_EXAME { get; set; }
        public Nullable<System.DateTime> DATA_AGENDAMENTO { get; set; }
        public Nullable<System.DateTime> DATA_CHEGADA { get; set; }
        public Nullable<System.DateTime> DATA_RETIRADO { get; set; }
        public string NOME_RETIROU { get; set; }
        public string COD_PRO { get; set; }
        public string NOME_PAC { get; set; }
        public string PROFISSIONAL { get; set; }
        public string STATUS { get; set; }
        public Nullable<int> CODIGO_EXAME { get; set; }
        public string COD_EXA_SUS { get; set; }
        public string NOME_EXAME { get; set; }
        public string LABORATORIO { get; set; }
        public Nullable<int> CNES_UNIDADE { get; set; }
        public string UNIDADE { get; set; }
        public Nullable<bool> URGENCIA { get; set; }
        public Nullable<System.DateTime> DATA_INSERT { get; set; }
        public Nullable<System.DateTime> DT_ULT_ATUALIZACAO { get; set; }
        public Nullable<System.Guid> CODIGO_QR { get; set; }
        public Nullable<bool> IMPORTADO_STATUS { get; set; }
    }
}
