//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAVORITOS
    {
        public int ID { get; set; }
        public Nullable<int> FK_RELACAO_NUMERICA { get; set; }
        public Nullable<System.DateTime> DATA_LIGACAO { get; set; }
        public Nullable<System.TimeSpan> HORA { get; set; }
        public Nullable<int> FK_TIPO_FAVORITOS { get; set; }
        public string RETORNO { get; set; }
        public string TELEFONE { get; set; }
        public string IDUSER { get; set; }
    }
}
