//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FITASVISUAL
    {
        public int Id { get; set; }
        public int FK_INSPECAOMATERIAL { get; set; }
        public string CORTES { get; set; }
        public string DESCOLORACAO { get; set; }
        public string DESGASTES { get; set; }
        public string FERRUGEM { get; set; }
        public string MANCHA { get; set; }
        public string PARTES_RIGIDAS { get; set; }
        public string QUEIMADURAS { get; set; }
    }
}
