//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class L_DOCUMENTO_ASSINATURA
    {
        public int ID { get; set; }
        public string NOME_DOCUMENTO { get; set; }
        public Nullable<System.DateTime> DATA_ENVIO { get; set; }
        public string MATRICULA { get; set; }
        public string CLIENTE { get; set; }
        public string DOWNLOAD { get; set; }
        public string CHAVE { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.Guid> COD_DISTRIBUICAO { get; set; }
    }
}
