//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class L_ENVIO_PARA_HIGIENIZACAO
    {
        public int ID { get; set; }
        public Nullable<int> FK_MOVIMENTACAO { get; set; }
        public string EPC { get; set; }
        public Nullable<System.DateTime> DATA { get; set; }
        public string ART { get; set; }
        public Nullable<System.DateTime> DATA_PROXIMO_TESTE { get; set; }
        public string TESTE { get; set; }
        public Nullable<System.DateTime> DATA_RETORNO { get; set; }
    }
}
