//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class L_INSPECAOFUNCIONARIO
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> DATA_INSPECAO { get; set; }
        public string COD_FUNCIONARIO { get; set; }
        public string FUNCIONARIO { get; set; }
        public string MOTIVO { get; set; }
        public string EPC { get; set; }
        public string COD_PRODUTO { get; set; }
        public string DESC_PRODUTO { get; set; }
        public Nullable<System.DateTime> DATA_VALIDADE { get; set; }
        public Nullable<System.DateTime> DATA_VALIDADETESTE { get; set; }
        public string COD_INSPECAO { get; set; }
        public string LAT { get; set; }
        public string LONG { get; set; }
    }
}
