//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class L_LOGIN
    {
        public int ID { get; set; }
        public string USUARIO { get; set; }
        public string SENHA { get; set; }
        public string NOME { get; set; }
        public Nullable<int> FK_PERFIL { get; set; }
        public Nullable<int> FK_USUARIO { get; set; }
        public string USUARIO_CHAVE { get; set; }
        public string P_ACESSO { get; set; }
    }
}
