//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class L_MANUTENCAOEPI
    {
        public int ID { get; set; }
        public string EPC { get; set; }
        public Nullable<System.DateTime> DATA_MANUTENCAO { get; set; }
        public string STATUS { get; set; }
    }
}
