//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class L_PACOTES_ASSINATURA
    {
        public int ID { get; set; }
        public string PACOTE { get; set; }
        public string VALOR { get; set; }
        public Nullable<int> QTD_ASSINATURAS { get; set; }
    }
}
