//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class L_PACOTE_ASSINATURA
    {
        public int ID { get; set; }
        public Nullable<int> QTD_ASSINATURA { get; set; }
        public Nullable<int> FK_CLIENTE { get; set; }
        public Nullable<System.DateTime> DATA { get; set; }
        public Nullable<System.DateTime> EXPIRA { get; set; }
        public Nullable<int> QTD_ASSINADOS { get; set; }
        public Nullable<int> QTD_FALTA_ASSINAR { get; set; }
    }
}
