//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class L_PRODUTOS_copy
    {
        public int ID { get; set; }
        public string COD_PRODUTO { get; set; }
        public string PRODUTO { get; set; }
        public Nullable<System.DateTime> DT_VALIDADE { get; set; }
        public string COD_FORNECEDOR { get; set; }
        public Nullable<System.DateTime> DT_FABRICACAO { get; set; }
        public string CA { get; set; }
        public string NUMERO_LOTE { get; set; }
        public Nullable<System.DateTime> VALIDADE_TESTE { get; set; }
        public string EPC { get; set; }
        public Nullable<int> NUMERO_NOTA { get; set; }
        public string COD_CLIENTE { get; set; }
        public Nullable<System.DateTime> DATA_INSERT { get; set; }
        public string CNPJ_EMITENTE { get; set; }
        public string CNPJ_DESTINATARIO { get; set; }
        public string GRUPO_CLIENTE { get; set; }
        public string NORMA { get; set; }
    }
}
