//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class L_TELAS_PERFIL
    {
        public int ID { get; set; }
        public Nullable<int> FK_TELAS { get; set; }
        public Nullable<int> FK_PERFIL { get; set; }
    }
}
