//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class L_USUARIOS
    {
        public int ID { get; set; }
        public string NOME { get; set; }
        public string USUARIO { get; set; }
        public string SENHA { get; set; }
        public string STATUS { get; set; }
        public string EMAIL { get; set; }
        public string RECEBE_EMAIL { get; set; }
        public string LOCAL_ESTOQUE { get; set; }
    }
}
