//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class LABEXA
    {
        public int COD_LAB { get; set; }
        public string NOME { get; set; }
        public string TELEFONE { get; set; }
        public string CIDADE { get; set; }
        public string ENDERECO { get; set; }
        public string RESPONSAVEL { get; set; }
        public string TIPO_C_V { get; set; }
        public Nullable<float> VALORTOTAL { get; set; }
        public Nullable<bool> ATIVO { get; set; }
    }
}
