//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class webservicetwos3Entities : DbContext
    {
        public webservicetwos3Entities()
            : base("name=webservicetwos3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<L_DESCARTE> L_DESCARTE { get; set; }
        public virtual DbSet<L_EPCPERDIDOS> L_EPCPERDIDOS { get; set; }
        public virtual DbSet<L_ESTOQUE> L_ESTOQUE { get; set; }
        public virtual DbSet<L_FUNCAO_PRODUTOS> L_FUNCAO_PRODUTOS { get; set; }
        public virtual DbSet<L_FUNCIONARIOS> L_FUNCIONARIOS { get; set; }
        public virtual DbSet<L_FUNCOES> L_FUNCOES { get; set; }
        public virtual DbSet<L_INSPECAOFUNCIONARIO> L_INSPECAOFUNCIONARIO { get; set; }
        public virtual DbSet<L_INSPITEM> L_INSPITEM { get; set; }
        public virtual DbSet<L_LOCALESTOQUE> L_LOCALESTOQUE { get; set; }
        public virtual DbSet<L_LOGIN> L_LOGIN { get; set; }
        public virtual DbSet<L_MOVIMENTACAO_ESTOQUE> L_MOVIMENTACAO_ESTOQUE { get; set; }
        public virtual DbSet<L_PERFIL> L_PERFIL { get; set; }
        public virtual DbSet<L_PRODUTOS> L_PRODUTOS { get; set; }
        public virtual DbSet<L_PRODUTOS_ITENS> L_PRODUTOS_ITENS { get; set; }
        public virtual DbSet<L_TELAS> L_TELAS { get; set; }
        public virtual DbSet<L_TELAS_PERFIL> L_TELAS_PERFIL { get; set; }
        public virtual DbSet<L_USUARIO_COLABORADOR> L_USUARIO_COLABORADOR { get; set; }
        public virtual DbSet<L_USUARIOS> L_USUARIOS { get; set; }
        public virtual DbSet<L_ENVIO_PARA_TESTE> L_ENVIO_PARA_TESTE { get; set; }
        public virtual DbSet<L_ATRIBUICAOCRACHA> L_ATRIBUICAOCRACHA { get; set; }
        public virtual DbSet<L_NAOCONFORMIDADE> L_NAOCONFORMIDADE { get; set; }
        public virtual DbSet<L_MANUTENCAOEPI> L_MANUTENCAOEPI { get; set; }
        public virtual DbSet<L_LOGIN_FUNCIONARIO> L_LOGIN_FUNCIONARIO { get; set; }
        public virtual DbSet<L_MENSAGEM_OCORRENCIA> L_MENSAGEM_OCORRENCIA { get; set; }
        public virtual DbSet<L_FICHACADASTRAL> L_FICHACADASTRAL { get; set; }
        public virtual DbSet<L_STATUSOCORRENCIA> L_STATUSOCORRENCIA { get; set; }
        public virtual DbSet<L_CLIENTE> L_CLIENTE { get; set; }
        public virtual DbSet<L_PACOTE_ASSINATURA_DOCUMENTOS> L_PACOTE_ASSINATURA_DOCUMENTOS { get; set; }
        public virtual DbSet<L_DOCUMENTO_ASSINATURA> L_DOCUMENTO_ASSINATURA { get; set; }
        public virtual DbSet<L_PACOTE_ASSINATURA_CLIENTE> L_PACOTE_ASSINATURA_CLIENTE { get; set; }
        public virtual DbSet<L_PACOTES_ASSINATURA> L_PACOTES_ASSINATURA { get; set; }
        public virtual DbSet<L_ENVIO_PARA_HIGIENIZACAO> L_ENVIO_PARA_HIGIENIZACAO { get; set; }
        public virtual DbSet<L_PACOTE_ASSINATURA> L_PACOTE_ASSINATURA { get; set; }
        public virtual DbSet<SessaoUsuario> SessaoUsuario { get; set; }
    }
}
