//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_USUARIO_COALBORADOR
    {
        public int id { get; set; }
        public string nome { get; set; }
        public string email { get; set; }
        public string telefone { get; set; }
        public string cnpj { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> perfil { get; set; }
        public string senha { get; set; }
        public string chaveAtivacao { get; set; }
        public string ativo { get; set; }
        public Nullable<System.DateTime> dataCadastro { get; set; }
        public string ativoAdministrado { get; set; }
        public string usuario_chave { get; set; }
        public string usuario { get; set; }
        public Nullable<int> local_estoque { get; set; }
        public string receberEmail { get; set; }
    }
}
