//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECLAME
    {
        public int ID { get; set; }
        public string MOTIVO { get; set; }
        public string DESCRICAO { get; set; }
        public Nullable<int> TIPO_RECLAME { get; set; }
        public string LATITUDE { get; set; }
        public string LONGITUDE { get; set; }
        public Nullable<System.DateTime> DATA { get; set; }
    }
}
