//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class REL_CARGO_CARGSEC
    {
        public int ID { get; set; }
        public Nullable<int> FK_CARGOS { get; set; }
        public Nullable<int> FK_CARGOS_SEC { get; set; }
        public string CARGO_SEC { get; set; }
        public byte[] foto { get; set; }
    }
}
