//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessaoUsuario
    {
        public int ID { get; set; }
        public string SessionId { get; set; }
        public string nomeFuncionario { get; set; }
        public string senhaFuncionario { get; set; }
        public string pAcesso { get; set; }
        public string fkCnpj { get; set; }
        public string Cnpj { get; set; }
        public string NomeEmpresa { get; set; }
        public string autenticado { get; set; }
        public string codigoFuncionario { get; set; }
        public Nullable<System.DateTime> DATA { get; set; }
    }
}
