//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEICULO_HORA
    {
        public int COD_VEI_HOR { get; set; }
        public Nullable<int> COD_VEI { get; set; }
        public string STATUS { get; set; }
        public string SAIDA { get; set; }
        public string RETORNO { get; set; }
        public string ODOMETROS { get; set; }
        public string ODOMETROR { get; set; }
        public Nullable<System.DateTime> DATA { get; set; }
        public Nullable<int> COD_UNI { get; set; }
        public string OBSMOTORISTA { get; set; }
        public Nullable<System.DateTime> DATA_SAIDA { get; set; }
        public Nullable<System.DateTime> DATA_CHEGADA { get; set; }
        public Nullable<int> KM_INI { get; set; }
        public Nullable<int> KM_CHEGADA { get; set; }
    }
}
