//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WebApplication1.Primario {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ClientSoap", Namespace="http://tempuri.org/")]
    public partial class Client : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback retornaLocalEstoqueOperationCompleted;
        
        private System.Threading.SendOrPostCallback movimentacaoEstoqueOperationCompleted;
        
        private System.Threading.SendOrPostCallback recebimentoEstoqueOperationCompleted;
        
        private System.Threading.SendOrPostCallback atribuicaoCrachaOperationCompleted;
        
        private System.Threading.SendOrPostCallback distribuicaoEPIOperationCompleted;
        
        private System.Threading.SendOrPostCallback envioParaTesteOperationCompleted;
        
        private System.Threading.SendOrPostCallback recebimentoTesteOperationCompleted;
        
        private System.Threading.SendOrPostCallback inspecaoEPIFuncionarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback itemNaoConformeOperationCompleted;
        
        private System.Threading.SendOrPostCallback manutencaoEPIOperationCompleted;
        
        private System.Threading.SendOrPostCallback funcionarioCrachaOperationCompleted;
        
        private System.Threading.SendOrPostCallback FuncionarioTemSenhaOperationCompleted;
        
        private System.Threading.SendOrPostCallback cadastrarSenhaOperationCompleted;
        
        private System.Threading.SendOrPostCallback loginFuncionarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback devolucaoEPIOperationCompleted;
        
        private System.Threading.SendOrPostCallback descartarItemOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultaEPIOperationCompleted;
        
        private System.Threading.SendOrPostCallback retornarDadosEpiOperationCompleted;
        
        private System.Threading.SendOrPostCallback dateDiffTesteOperationCompleted;
        
        private System.Threading.SendOrPostCallback importacaoDeDadosOperationCompleted;
        
        private System.Threading.SendOrPostCallback retornarDadosEpiValidarOperationCompleted;
        
        private System.Threading.SendOrPostCallback salvarMensagemOcorrenciaOperationCompleted;
        
        private System.Threading.SendOrPostCallback retornarListaMensagemOperationCompleted;
        
        private System.Threading.SendOrPostCallback retornarListaMensagemSupervisorOperationCompleted;
        
        private System.Threading.SendOrPostCallback alterarStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback dataDifOperationCompleted;
        
        private System.Threading.SendOrPostCallback retornarDadosEpiValidarRecebimentoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Client() {
            this.Url = global::WebApplication1.Properties.Settings.Default.WebApplication1_Primario_Client;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event retornaLocalEstoqueCompletedEventHandler retornaLocalEstoqueCompleted;
        
        /// <remarks/>
        public event movimentacaoEstoqueCompletedEventHandler movimentacaoEstoqueCompleted;
        
        /// <remarks/>
        public event recebimentoEstoqueCompletedEventHandler recebimentoEstoqueCompleted;
        
        /// <remarks/>
        public event atribuicaoCrachaCompletedEventHandler atribuicaoCrachaCompleted;
        
        /// <remarks/>
        public event distribuicaoEPICompletedEventHandler distribuicaoEPICompleted;
        
        /// <remarks/>
        public event envioParaTesteCompletedEventHandler envioParaTesteCompleted;
        
        /// <remarks/>
        public event recebimentoTesteCompletedEventHandler recebimentoTesteCompleted;
        
        /// <remarks/>
        public event inspecaoEPIFuncionarioCompletedEventHandler inspecaoEPIFuncionarioCompleted;
        
        /// <remarks/>
        public event itemNaoConformeCompletedEventHandler itemNaoConformeCompleted;
        
        /// <remarks/>
        public event manutencaoEPICompletedEventHandler manutencaoEPICompleted;
        
        /// <remarks/>
        public event funcionarioCrachaCompletedEventHandler funcionarioCrachaCompleted;
        
        /// <remarks/>
        public event FuncionarioTemSenhaCompletedEventHandler FuncionarioTemSenhaCompleted;
        
        /// <remarks/>
        public event cadastrarSenhaCompletedEventHandler cadastrarSenhaCompleted;
        
        /// <remarks/>
        public event loginFuncionarioCompletedEventHandler loginFuncionarioCompleted;
        
        /// <remarks/>
        public event devolucaoEPICompletedEventHandler devolucaoEPICompleted;
        
        /// <remarks/>
        public event descartarItemCompletedEventHandler descartarItemCompleted;
        
        /// <remarks/>
        public event consultaEPICompletedEventHandler consultaEPICompleted;
        
        /// <remarks/>
        public event retornarDadosEpiCompletedEventHandler retornarDadosEpiCompleted;
        
        /// <remarks/>
        public event dateDiffTesteCompletedEventHandler dateDiffTesteCompleted;
        
        /// <remarks/>
        public event importacaoDeDadosCompletedEventHandler importacaoDeDadosCompleted;
        
        /// <remarks/>
        public event retornarDadosEpiValidarCompletedEventHandler retornarDadosEpiValidarCompleted;
        
        /// <remarks/>
        public event salvarMensagemOcorrenciaCompletedEventHandler salvarMensagemOcorrenciaCompleted;
        
        /// <remarks/>
        public event retornarListaMensagemCompletedEventHandler retornarListaMensagemCompleted;
        
        /// <remarks/>
        public event retornarListaMensagemSupervisorCompletedEventHandler retornarListaMensagemSupervisorCompleted;
        
        /// <remarks/>
        public event alterarStatusCompletedEventHandler alterarStatusCompleted;
        
        /// <remarks/>
        public event dataDifCompletedEventHandler dataDifCompleted;
        
        /// <remarks/>
        public event retornarDadosEpiValidarRecebimentoCompletedEventHandler retornarDadosEpiValidarRecebimentoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/retornaLocalEstoque", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public L_LOCALESTOQUE[] retornaLocalEstoque() {
            object[] results = this.Invoke("retornaLocalEstoque", new object[0]);
            return ((L_LOCALESTOQUE[])(results[0]));
        }
        
        /// <remarks/>
        public void retornaLocalEstoqueAsync() {
            this.retornaLocalEstoqueAsync(null);
        }
        
        /// <remarks/>
        public void retornaLocalEstoqueAsync(object userState) {
            if ((this.retornaLocalEstoqueOperationCompleted == null)) {
                this.retornaLocalEstoqueOperationCompleted = new System.Threading.SendOrPostCallback(this.OnretornaLocalEstoqueOperationCompleted);
            }
            this.InvokeAsync("retornaLocalEstoque", new object[0], this.retornaLocalEstoqueOperationCompleted, userState);
        }
        
        private void OnretornaLocalEstoqueOperationCompleted(object arg) {
            if ((this.retornaLocalEstoqueCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.retornaLocalEstoqueCompleted(this, new retornaLocalEstoqueCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/movimentacaoEstoque", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RESULTADOMOV[] movimentacaoEstoque(string listaEPCS, string estoque, string entSaida) {
            object[] results = this.Invoke("movimentacaoEstoque", new object[] {
                        listaEPCS,
                        estoque,
                        entSaida});
            return ((RESULTADOMOV[])(results[0]));
        }
        
        /// <remarks/>
        public void movimentacaoEstoqueAsync(string listaEPCS, string estoque, string entSaida) {
            this.movimentacaoEstoqueAsync(listaEPCS, estoque, entSaida, null);
        }
        
        /// <remarks/>
        public void movimentacaoEstoqueAsync(string listaEPCS, string estoque, string entSaida, object userState) {
            if ((this.movimentacaoEstoqueOperationCompleted == null)) {
                this.movimentacaoEstoqueOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmovimentacaoEstoqueOperationCompleted);
            }
            this.InvokeAsync("movimentacaoEstoque", new object[] {
                        listaEPCS,
                        estoque,
                        entSaida}, this.movimentacaoEstoqueOperationCompleted, userState);
        }
        
        private void OnmovimentacaoEstoqueOperationCompleted(object arg) {
            if ((this.movimentacaoEstoqueCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.movimentacaoEstoqueCompleted(this, new movimentacaoEstoqueCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/recebimentoEstoque", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RESULTADOMOV[] recebimentoEstoque(string listaEPCS) {
            object[] results = this.Invoke("recebimentoEstoque", new object[] {
                        listaEPCS});
            return ((RESULTADOMOV[])(results[0]));
        }
        
        /// <remarks/>
        public void recebimentoEstoqueAsync(string listaEPCS) {
            this.recebimentoEstoqueAsync(listaEPCS, null);
        }
        
        /// <remarks/>
        public void recebimentoEstoqueAsync(string listaEPCS, object userState) {
            if ((this.recebimentoEstoqueOperationCompleted == null)) {
                this.recebimentoEstoqueOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrecebimentoEstoqueOperationCompleted);
            }
            this.InvokeAsync("recebimentoEstoque", new object[] {
                        listaEPCS}, this.recebimentoEstoqueOperationCompleted, userState);
        }
        
        private void OnrecebimentoEstoqueOperationCompleted(object arg) {
            if ((this.recebimentoEstoqueCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.recebimentoEstoqueCompleted(this, new recebimentoEstoqueCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/atribuicaoCracha", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RESULTADOMOV[] atribuicaoCracha(string matricula, string cracha) {
            object[] results = this.Invoke("atribuicaoCracha", new object[] {
                        matricula,
                        cracha});
            return ((RESULTADOMOV[])(results[0]));
        }
        
        /// <remarks/>
        public void atribuicaoCrachaAsync(string matricula, string cracha) {
            this.atribuicaoCrachaAsync(matricula, cracha, null);
        }
        
        /// <remarks/>
        public void atribuicaoCrachaAsync(string matricula, string cracha, object userState) {
            if ((this.atribuicaoCrachaOperationCompleted == null)) {
                this.atribuicaoCrachaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnatribuicaoCrachaOperationCompleted);
            }
            this.InvokeAsync("atribuicaoCracha", new object[] {
                        matricula,
                        cracha}, this.atribuicaoCrachaOperationCompleted, userState);
        }
        
        private void OnatribuicaoCrachaOperationCompleted(object arg) {
            if ((this.atribuicaoCrachaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.atribuicaoCrachaCompleted(this, new atribuicaoCrachaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/distribuicaoEPI", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RESULTADOMOV[] distribuicaoEPI(string listaEPCS, string matricula) {
            object[] results = this.Invoke("distribuicaoEPI", new object[] {
                        listaEPCS,
                        matricula});
            return ((RESULTADOMOV[])(results[0]));
        }
        
        /// <remarks/>
        public void distribuicaoEPIAsync(string listaEPCS, string matricula) {
            this.distribuicaoEPIAsync(listaEPCS, matricula, null);
        }
        
        /// <remarks/>
        public void distribuicaoEPIAsync(string listaEPCS, string matricula, object userState) {
            if ((this.distribuicaoEPIOperationCompleted == null)) {
                this.distribuicaoEPIOperationCompleted = new System.Threading.SendOrPostCallback(this.OndistribuicaoEPIOperationCompleted);
            }
            this.InvokeAsync("distribuicaoEPI", new object[] {
                        listaEPCS,
                        matricula}, this.distribuicaoEPIOperationCompleted, userState);
        }
        
        private void OndistribuicaoEPIOperationCompleted(object arg) {
            if ((this.distribuicaoEPICompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.distribuicaoEPICompleted(this, new distribuicaoEPICompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/envioParaTeste", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RESULTADOMOV[] envioParaTeste(string listaEPCS, string estoque) {
            object[] results = this.Invoke("envioParaTeste", new object[] {
                        listaEPCS,
                        estoque});
            return ((RESULTADOMOV[])(results[0]));
        }
        
        /// <remarks/>
        public void envioParaTesteAsync(string listaEPCS, string estoque) {
            this.envioParaTesteAsync(listaEPCS, estoque, null);
        }
        
        /// <remarks/>
        public void envioParaTesteAsync(string listaEPCS, string estoque, object userState) {
            if ((this.envioParaTesteOperationCompleted == null)) {
                this.envioParaTesteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnenvioParaTesteOperationCompleted);
            }
            this.InvokeAsync("envioParaTeste", new object[] {
                        listaEPCS,
                        estoque}, this.envioParaTesteOperationCompleted, userState);
        }
        
        private void OnenvioParaTesteOperationCompleted(object arg) {
            if ((this.envioParaTesteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.envioParaTesteCompleted(this, new envioParaTesteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/recebimentoTeste", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RESULTADOMOV[] recebimentoTeste(string listaEPCS, string dataTeste, string art) {
            object[] results = this.Invoke("recebimentoTeste", new object[] {
                        listaEPCS,
                        dataTeste,
                        art});
            return ((RESULTADOMOV[])(results[0]));
        }
        
        /// <remarks/>
        public void recebimentoTesteAsync(string listaEPCS, string dataTeste, string art) {
            this.recebimentoTesteAsync(listaEPCS, dataTeste, art, null);
        }
        
        /// <remarks/>
        public void recebimentoTesteAsync(string listaEPCS, string dataTeste, string art, object userState) {
            if ((this.recebimentoTesteOperationCompleted == null)) {
                this.recebimentoTesteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrecebimentoTesteOperationCompleted);
            }
            this.InvokeAsync("recebimentoTeste", new object[] {
                        listaEPCS,
                        dataTeste,
                        art}, this.recebimentoTesteOperationCompleted, userState);
        }
        
        private void OnrecebimentoTesteOperationCompleted(object arg) {
            if ((this.recebimentoTesteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.recebimentoTesteCompleted(this, new recebimentoTesteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/inspecaoEPIFuncionario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RESULTADOMOV[] inspecaoEPIFuncionario(string listaEPCS, string latitude, string longitude) {
            object[] results = this.Invoke("inspecaoEPIFuncionario", new object[] {
                        listaEPCS,
                        latitude,
                        longitude});
            return ((RESULTADOMOV[])(results[0]));
        }
        
        /// <remarks/>
        public void inspecaoEPIFuncionarioAsync(string listaEPCS, string latitude, string longitude) {
            this.inspecaoEPIFuncionarioAsync(listaEPCS, latitude, longitude, null);
        }
        
        /// <remarks/>
        public void inspecaoEPIFuncionarioAsync(string listaEPCS, string latitude, string longitude, object userState) {
            if ((this.inspecaoEPIFuncionarioOperationCompleted == null)) {
                this.inspecaoEPIFuncionarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OninspecaoEPIFuncionarioOperationCompleted);
            }
            this.InvokeAsync("inspecaoEPIFuncionario", new object[] {
                        listaEPCS,
                        latitude,
                        longitude}, this.inspecaoEPIFuncionarioOperationCompleted, userState);
        }
        
        private void OninspecaoEPIFuncionarioOperationCompleted(object arg) {
            if ((this.inspecaoEPIFuncionarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.inspecaoEPIFuncionarioCompleted(this, new inspecaoEPIFuncionarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/itemNaoConforme", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RESULTADOMOV[] itemNaoConforme(string listaEPCS, string motivo) {
            object[] results = this.Invoke("itemNaoConforme", new object[] {
                        listaEPCS,
                        motivo});
            return ((RESULTADOMOV[])(results[0]));
        }
        
        /// <remarks/>
        public void itemNaoConformeAsync(string listaEPCS, string motivo) {
            this.itemNaoConformeAsync(listaEPCS, motivo, null);
        }
        
        /// <remarks/>
        public void itemNaoConformeAsync(string listaEPCS, string motivo, object userState) {
            if ((this.itemNaoConformeOperationCompleted == null)) {
                this.itemNaoConformeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnitemNaoConformeOperationCompleted);
            }
            this.InvokeAsync("itemNaoConforme", new object[] {
                        listaEPCS,
                        motivo}, this.itemNaoConformeOperationCompleted, userState);
        }
        
        private void OnitemNaoConformeOperationCompleted(object arg) {
            if ((this.itemNaoConformeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.itemNaoConformeCompleted(this, new itemNaoConformeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/manutencaoEPI", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RESULTADOMOV[] manutencaoEPI(string listaEPCS, string estoque) {
            object[] results = this.Invoke("manutencaoEPI", new object[] {
                        listaEPCS,
                        estoque});
            return ((RESULTADOMOV[])(results[0]));
        }
        
        /// <remarks/>
        public void manutencaoEPIAsync(string listaEPCS, string estoque) {
            this.manutencaoEPIAsync(listaEPCS, estoque, null);
        }
        
        /// <remarks/>
        public void manutencaoEPIAsync(string listaEPCS, string estoque, object userState) {
            if ((this.manutencaoEPIOperationCompleted == null)) {
                this.manutencaoEPIOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmanutencaoEPIOperationCompleted);
            }
            this.InvokeAsync("manutencaoEPI", new object[] {
                        listaEPCS,
                        estoque}, this.manutencaoEPIOperationCompleted, userState);
        }
        
        private void OnmanutencaoEPIOperationCompleted(object arg) {
            if ((this.manutencaoEPICompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.manutencaoEPICompleted(this, new manutencaoEPICompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/funcionarioCracha", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RESULTADOMOV[] funcionarioCracha(string cracha) {
            object[] results = this.Invoke("funcionarioCracha", new object[] {
                        cracha});
            return ((RESULTADOMOV[])(results[0]));
        }
        
        /// <remarks/>
        public void funcionarioCrachaAsync(string cracha) {
            this.funcionarioCrachaAsync(cracha, null);
        }
        
        /// <remarks/>
        public void funcionarioCrachaAsync(string cracha, object userState) {
            if ((this.funcionarioCrachaOperationCompleted == null)) {
                this.funcionarioCrachaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfuncionarioCrachaOperationCompleted);
            }
            this.InvokeAsync("funcionarioCracha", new object[] {
                        cracha}, this.funcionarioCrachaOperationCompleted, userState);
        }
        
        private void OnfuncionarioCrachaOperationCompleted(object arg) {
            if ((this.funcionarioCrachaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.funcionarioCrachaCompleted(this, new funcionarioCrachaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FuncionarioTemSenha", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool FuncionarioTemSenha(string listaEPCS) {
            object[] results = this.Invoke("FuncionarioTemSenha", new object[] {
                        listaEPCS});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void FuncionarioTemSenhaAsync(string listaEPCS) {
            this.FuncionarioTemSenhaAsync(listaEPCS, null);
        }
        
        /// <remarks/>
        public void FuncionarioTemSenhaAsync(string listaEPCS, object userState) {
            if ((this.FuncionarioTemSenhaOperationCompleted == null)) {
                this.FuncionarioTemSenhaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFuncionarioTemSenhaOperationCompleted);
            }
            this.InvokeAsync("FuncionarioTemSenha", new object[] {
                        listaEPCS}, this.FuncionarioTemSenhaOperationCompleted, userState);
        }
        
        private void OnFuncionarioTemSenhaOperationCompleted(object arg) {
            if ((this.FuncionarioTemSenhaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FuncionarioTemSenhaCompleted(this, new FuncionarioTemSenhaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/cadastrarSenha", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RESULTADOMOV[] cadastrarSenha(string senha, string matricula) {
            object[] results = this.Invoke("cadastrarSenha", new object[] {
                        senha,
                        matricula});
            return ((RESULTADOMOV[])(results[0]));
        }
        
        /// <remarks/>
        public void cadastrarSenhaAsync(string senha, string matricula) {
            this.cadastrarSenhaAsync(senha, matricula, null);
        }
        
        /// <remarks/>
        public void cadastrarSenhaAsync(string senha, string matricula, object userState) {
            if ((this.cadastrarSenhaOperationCompleted == null)) {
                this.cadastrarSenhaOperationCompleted = new System.Threading.SendOrPostCallback(this.OncadastrarSenhaOperationCompleted);
            }
            this.InvokeAsync("cadastrarSenha", new object[] {
                        senha,
                        matricula}, this.cadastrarSenhaOperationCompleted, userState);
        }
        
        private void OncadastrarSenhaOperationCompleted(object arg) {
            if ((this.cadastrarSenhaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cadastrarSenhaCompleted(this, new cadastrarSenhaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/loginFuncionario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RESULTADOMOV[] loginFuncionario(string matricula, string senha) {
            object[] results = this.Invoke("loginFuncionario", new object[] {
                        matricula,
                        senha});
            return ((RESULTADOMOV[])(results[0]));
        }
        
        /// <remarks/>
        public void loginFuncionarioAsync(string matricula, string senha) {
            this.loginFuncionarioAsync(matricula, senha, null);
        }
        
        /// <remarks/>
        public void loginFuncionarioAsync(string matricula, string senha, object userState) {
            if ((this.loginFuncionarioOperationCompleted == null)) {
                this.loginFuncionarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnloginFuncionarioOperationCompleted);
            }
            this.InvokeAsync("loginFuncionario", new object[] {
                        matricula,
                        senha}, this.loginFuncionarioOperationCompleted, userState);
        }
        
        private void OnloginFuncionarioOperationCompleted(object arg) {
            if ((this.loginFuncionarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.loginFuncionarioCompleted(this, new loginFuncionarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/devolucaoEPI", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RESULTADOMOV[] devolucaoEPI(string listaEPCS, string estoque) {
            object[] results = this.Invoke("devolucaoEPI", new object[] {
                        listaEPCS,
                        estoque});
            return ((RESULTADOMOV[])(results[0]));
        }
        
        /// <remarks/>
        public void devolucaoEPIAsync(string listaEPCS, string estoque) {
            this.devolucaoEPIAsync(listaEPCS, estoque, null);
        }
        
        /// <remarks/>
        public void devolucaoEPIAsync(string listaEPCS, string estoque, object userState) {
            if ((this.devolucaoEPIOperationCompleted == null)) {
                this.devolucaoEPIOperationCompleted = new System.Threading.SendOrPostCallback(this.OndevolucaoEPIOperationCompleted);
            }
            this.InvokeAsync("devolucaoEPI", new object[] {
                        listaEPCS,
                        estoque}, this.devolucaoEPIOperationCompleted, userState);
        }
        
        private void OndevolucaoEPIOperationCompleted(object arg) {
            if ((this.devolucaoEPICompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.devolucaoEPICompleted(this, new devolucaoEPICompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/descartarItem", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RESULTADOMOV[] descartarItem(string listaEPCS, string motivo) {
            object[] results = this.Invoke("descartarItem", new object[] {
                        listaEPCS,
                        motivo});
            return ((RESULTADOMOV[])(results[0]));
        }
        
        /// <remarks/>
        public void descartarItemAsync(string listaEPCS, string motivo) {
            this.descartarItemAsync(listaEPCS, motivo, null);
        }
        
        /// <remarks/>
        public void descartarItemAsync(string listaEPCS, string motivo, object userState) {
            if ((this.descartarItemOperationCompleted == null)) {
                this.descartarItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OndescartarItemOperationCompleted);
            }
            this.InvokeAsync("descartarItem", new object[] {
                        listaEPCS,
                        motivo}, this.descartarItemOperationCompleted, userState);
        }
        
        private void OndescartarItemOperationCompleted(object arg) {
            if ((this.descartarItemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.descartarItemCompleted(this, new descartarItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/consultaEPI", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RESULTADOMOV[] consultaEPI(string listaEPCS) {
            object[] results = this.Invoke("consultaEPI", new object[] {
                        listaEPCS});
            return ((RESULTADOMOV[])(results[0]));
        }
        
        /// <remarks/>
        public void consultaEPIAsync(string listaEPCS) {
            this.consultaEPIAsync(listaEPCS, null);
        }
        
        /// <remarks/>
        public void consultaEPIAsync(string listaEPCS, object userState) {
            if ((this.consultaEPIOperationCompleted == null)) {
                this.consultaEPIOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultaEPIOperationCompleted);
            }
            this.InvokeAsync("consultaEPI", new object[] {
                        listaEPCS}, this.consultaEPIOperationCompleted, userState);
        }
        
        private void OnconsultaEPIOperationCompleted(object arg) {
            if ((this.consultaEPICompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultaEPICompleted(this, new consultaEPICompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/retornarDadosEpi", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RESULTADOMOV[] retornarDadosEpi(string listaEPCS) {
            object[] results = this.Invoke("retornarDadosEpi", new object[] {
                        listaEPCS});
            return ((RESULTADOMOV[])(results[0]));
        }
        
        /// <remarks/>
        public void retornarDadosEpiAsync(string listaEPCS) {
            this.retornarDadosEpiAsync(listaEPCS, null);
        }
        
        /// <remarks/>
        public void retornarDadosEpiAsync(string listaEPCS, object userState) {
            if ((this.retornarDadosEpiOperationCompleted == null)) {
                this.retornarDadosEpiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnretornarDadosEpiOperationCompleted);
            }
            this.InvokeAsync("retornarDadosEpi", new object[] {
                        listaEPCS}, this.retornarDadosEpiOperationCompleted, userState);
        }
        
        private void OnretornarDadosEpiOperationCompleted(object arg) {
            if ((this.retornarDadosEpiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.retornarDadosEpiCompleted(this, new retornarDadosEpiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/dateDiffTeste", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int dateDiffTeste(string data) {
            object[] results = this.Invoke("dateDiffTeste", new object[] {
                        data});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void dateDiffTesteAsync(string data) {
            this.dateDiffTesteAsync(data, null);
        }
        
        /// <remarks/>
        public void dateDiffTesteAsync(string data, object userState) {
            if ((this.dateDiffTesteOperationCompleted == null)) {
                this.dateDiffTesteOperationCompleted = new System.Threading.SendOrPostCallback(this.OndateDiffTesteOperationCompleted);
            }
            this.InvokeAsync("dateDiffTeste", new object[] {
                        data}, this.dateDiffTesteOperationCompleted, userState);
        }
        
        private void OndateDiffTesteOperationCompleted(object arg) {
            if ((this.dateDiffTesteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.dateDiffTesteCompleted(this, new dateDiffTesteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/importacaoDeDados", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string importacaoDeDados(L_PRODUTOS_ITENS lp) {
            object[] results = this.Invoke("importacaoDeDados", new object[] {
                        lp});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void importacaoDeDadosAsync(L_PRODUTOS_ITENS lp) {
            this.importacaoDeDadosAsync(lp, null);
        }
        
        /// <remarks/>
        public void importacaoDeDadosAsync(L_PRODUTOS_ITENS lp, object userState) {
            if ((this.importacaoDeDadosOperationCompleted == null)) {
                this.importacaoDeDadosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnimportacaoDeDadosOperationCompleted);
            }
            this.InvokeAsync("importacaoDeDados", new object[] {
                        lp}, this.importacaoDeDadosOperationCompleted, userState);
        }
        
        private void OnimportacaoDeDadosOperationCompleted(object arg) {
            if ((this.importacaoDeDadosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.importacaoDeDadosCompleted(this, new importacaoDeDadosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/retornarDadosEpiValidar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DADOSEPI[] retornarDadosEpiValidar(string listaEPCS) {
            object[] results = this.Invoke("retornarDadosEpiValidar", new object[] {
                        listaEPCS});
            return ((DADOSEPI[])(results[0]));
        }
        
        /// <remarks/>
        public void retornarDadosEpiValidarAsync(string listaEPCS) {
            this.retornarDadosEpiValidarAsync(listaEPCS, null);
        }
        
        /// <remarks/>
        public void retornarDadosEpiValidarAsync(string listaEPCS, object userState) {
            if ((this.retornarDadosEpiValidarOperationCompleted == null)) {
                this.retornarDadosEpiValidarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnretornarDadosEpiValidarOperationCompleted);
            }
            this.InvokeAsync("retornarDadosEpiValidar", new object[] {
                        listaEPCS}, this.retornarDadosEpiValidarOperationCompleted, userState);
        }
        
        private void OnretornarDadosEpiValidarOperationCompleted(object arg) {
            if ((this.retornarDadosEpiValidarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.retornarDadosEpiValidarCompleted(this, new retornarDadosEpiValidarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/salvarMensagemOcorrencia", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool salvarMensagemOcorrencia(string number, string mensagem) {
            object[] results = this.Invoke("salvarMensagemOcorrencia", new object[] {
                        number,
                        mensagem});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void salvarMensagemOcorrenciaAsync(string number, string mensagem) {
            this.salvarMensagemOcorrenciaAsync(number, mensagem, null);
        }
        
        /// <remarks/>
        public void salvarMensagemOcorrenciaAsync(string number, string mensagem, object userState) {
            if ((this.salvarMensagemOcorrenciaOperationCompleted == null)) {
                this.salvarMensagemOcorrenciaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsalvarMensagemOcorrenciaOperationCompleted);
            }
            this.InvokeAsync("salvarMensagemOcorrencia", new object[] {
                        number,
                        mensagem}, this.salvarMensagemOcorrenciaOperationCompleted, userState);
        }
        
        private void OnsalvarMensagemOcorrenciaOperationCompleted(object arg) {
            if ((this.salvarMensagemOcorrenciaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.salvarMensagemOcorrenciaCompleted(this, new salvarMensagemOcorrenciaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/retornarListaMensagem", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RESULTADOMOV[] retornarListaMensagem() {
            object[] results = this.Invoke("retornarListaMensagem", new object[0]);
            return ((RESULTADOMOV[])(results[0]));
        }
        
        /// <remarks/>
        public void retornarListaMensagemAsync() {
            this.retornarListaMensagemAsync(null);
        }
        
        /// <remarks/>
        public void retornarListaMensagemAsync(object userState) {
            if ((this.retornarListaMensagemOperationCompleted == null)) {
                this.retornarListaMensagemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnretornarListaMensagemOperationCompleted);
            }
            this.InvokeAsync("retornarListaMensagem", new object[0], this.retornarListaMensagemOperationCompleted, userState);
        }
        
        private void OnretornarListaMensagemOperationCompleted(object arg) {
            if ((this.retornarListaMensagemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.retornarListaMensagemCompleted(this, new retornarListaMensagemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/retornarListaMensagemSupervisor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RESULTADOMOV[] retornarListaMensagemSupervisor() {
            object[] results = this.Invoke("retornarListaMensagemSupervisor", new object[0]);
            return ((RESULTADOMOV[])(results[0]));
        }
        
        /// <remarks/>
        public void retornarListaMensagemSupervisorAsync() {
            this.retornarListaMensagemSupervisorAsync(null);
        }
        
        /// <remarks/>
        public void retornarListaMensagemSupervisorAsync(object userState) {
            if ((this.retornarListaMensagemSupervisorOperationCompleted == null)) {
                this.retornarListaMensagemSupervisorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnretornarListaMensagemSupervisorOperationCompleted);
            }
            this.InvokeAsync("retornarListaMensagemSupervisor", new object[0], this.retornarListaMensagemSupervisorOperationCompleted, userState);
        }
        
        private void OnretornarListaMensagemSupervisorOperationCompleted(object arg) {
            if ((this.retornarListaMensagemSupervisorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.retornarListaMensagemSupervisorCompleted(this, new retornarListaMensagemSupervisorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/alterarStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string alterarStatus(int id, string ocorrencia) {
            object[] results = this.Invoke("alterarStatus", new object[] {
                        id,
                        ocorrencia});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void alterarStatusAsync(int id, string ocorrencia) {
            this.alterarStatusAsync(id, ocorrencia, null);
        }
        
        /// <remarks/>
        public void alterarStatusAsync(int id, string ocorrencia, object userState) {
            if ((this.alterarStatusOperationCompleted == null)) {
                this.alterarStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnalterarStatusOperationCompleted);
            }
            this.InvokeAsync("alterarStatus", new object[] {
                        id,
                        ocorrencia}, this.alterarStatusOperationCompleted, userState);
        }
        
        private void OnalterarStatusOperationCompleted(object arg) {
            if ((this.alterarStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.alterarStatusCompleted(this, new alterarStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/dataDif", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string dataDif(string dt1) {
            object[] results = this.Invoke("dataDif", new object[] {
                        dt1});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void dataDifAsync(string dt1) {
            this.dataDifAsync(dt1, null);
        }
        
        /// <remarks/>
        public void dataDifAsync(string dt1, object userState) {
            if ((this.dataDifOperationCompleted == null)) {
                this.dataDifOperationCompleted = new System.Threading.SendOrPostCallback(this.OndataDifOperationCompleted);
            }
            this.InvokeAsync("dataDif", new object[] {
                        dt1}, this.dataDifOperationCompleted, userState);
        }
        
        private void OndataDifOperationCompleted(object arg) {
            if ((this.dataDifCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.dataDifCompleted(this, new dataDifCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/retornarDadosEpiValidarRecebimento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DADOSEPI[] retornarDadosEpiValidarRecebimento(string listaEPCS) {
            object[] results = this.Invoke("retornarDadosEpiValidarRecebimento", new object[] {
                        listaEPCS});
            return ((DADOSEPI[])(results[0]));
        }
        
        /// <remarks/>
        public void retornarDadosEpiValidarRecebimentoAsync(string listaEPCS) {
            this.retornarDadosEpiValidarRecebimentoAsync(listaEPCS, null);
        }
        
        /// <remarks/>
        public void retornarDadosEpiValidarRecebimentoAsync(string listaEPCS, object userState) {
            if ((this.retornarDadosEpiValidarRecebimentoOperationCompleted == null)) {
                this.retornarDadosEpiValidarRecebimentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnretornarDadosEpiValidarRecebimentoOperationCompleted);
            }
            this.InvokeAsync("retornarDadosEpiValidarRecebimento", new object[] {
                        listaEPCS}, this.retornarDadosEpiValidarRecebimentoOperationCompleted, userState);
        }
        
        private void OnretornarDadosEpiValidarRecebimentoOperationCompleted(object arg) {
            if ((this.retornarDadosEpiValidarRecebimentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.retornarDadosEpiValidarRecebimentoCompleted(this, new retornarDadosEpiValidarRecebimentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class L_LOCALESTOQUE {
        
        private int idField;
        
        private string cODIGOField;
        
        private string nOMEField;
        
        private string dESCRICAOField;
        
        private System.Nullable<System.DateTime> dATA_CADASTROField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string CODIGO {
            get {
                return this.cODIGOField;
            }
            set {
                this.cODIGOField = value;
            }
        }
        
        /// <remarks/>
        public string NOME {
            get {
                return this.nOMEField;
            }
            set {
                this.nOMEField = value;
            }
        }
        
        /// <remarks/>
        public string DESCRICAO {
            get {
                return this.dESCRICAOField;
            }
            set {
                this.dESCRICAOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DATA_CADASTRO {
            get {
                return this.dATA_CADASTROField;
            }
            set {
                this.dATA_CADASTROField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DADOSEPI {
        
        private string codFornecedorField;
        
        private string codProdutoField;
        
        private string ePCField;
        
        private string produtoField;
        
        private int qtdField;
        
        /// <remarks/>
        public string CodFornecedor {
            get {
                return this.codFornecedorField;
            }
            set {
                this.codFornecedorField = value;
            }
        }
        
        /// <remarks/>
        public string CodProduto {
            get {
                return this.codProdutoField;
            }
            set {
                this.codProdutoField = value;
            }
        }
        
        /// <remarks/>
        public string EPC {
            get {
                return this.ePCField;
            }
            set {
                this.ePCField = value;
            }
        }
        
        /// <remarks/>
        public string Produto {
            get {
                return this.produtoField;
            }
            set {
                this.produtoField = value;
            }
        }
        
        /// <remarks/>
        public int Qtd {
            get {
                return this.qtdField;
            }
            set {
                this.qtdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class L_PRODUTOS_ITENS {
        
        private int idField;
        
        private string cOD_PRODUTOField;
        
        private string pRODUTOField;
        
        private System.Nullable<System.DateTime> dT_VALIDADEField;
        
        private string cOD_FORNECEDORField;
        
        private System.Nullable<System.DateTime> dT_FABRICACAOField;
        
        private string caField;
        
        private string nUMERO_LOTEField;
        
        private System.Nullable<System.DateTime> vALIDADE_TESTEField;
        
        private string ePCField;
        
        private System.Nullable<System.DateTime> dATA_ENTRADAField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string COD_PRODUTO {
            get {
                return this.cOD_PRODUTOField;
            }
            set {
                this.cOD_PRODUTOField = value;
            }
        }
        
        /// <remarks/>
        public string PRODUTO {
            get {
                return this.pRODUTOField;
            }
            set {
                this.pRODUTOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DT_VALIDADE {
            get {
                return this.dT_VALIDADEField;
            }
            set {
                this.dT_VALIDADEField = value;
            }
        }
        
        /// <remarks/>
        public string COD_FORNECEDOR {
            get {
                return this.cOD_FORNECEDORField;
            }
            set {
                this.cOD_FORNECEDORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DT_FABRICACAO {
            get {
                return this.dT_FABRICACAOField;
            }
            set {
                this.dT_FABRICACAOField = value;
            }
        }
        
        /// <remarks/>
        public string CA {
            get {
                return this.caField;
            }
            set {
                this.caField = value;
            }
        }
        
        /// <remarks/>
        public string NUMERO_LOTE {
            get {
                return this.nUMERO_LOTEField;
            }
            set {
                this.nUMERO_LOTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> VALIDADE_TESTE {
            get {
                return this.vALIDADE_TESTEField;
            }
            set {
                this.vALIDADE_TESTEField = value;
            }
        }
        
        /// <remarks/>
        public string EPC {
            get {
                return this.ePCField;
            }
            set {
                this.ePCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DATA_ENTRADA {
            get {
                return this.dATA_ENTRADAField;
            }
            set {
                this.dATA_ENTRADAField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RESULTADOMOV {
        
        private System.DateTime dataMovimentacaoField;
        
        private string ePCField;
        
        private string produtoField;
        
        private string resultadoField;
        
        private string corAvisoField;
        
        /// <remarks/>
        public System.DateTime DataMovimentacao {
            get {
                return this.dataMovimentacaoField;
            }
            set {
                this.dataMovimentacaoField = value;
            }
        }
        
        /// <remarks/>
        public string EPC {
            get {
                return this.ePCField;
            }
            set {
                this.ePCField = value;
            }
        }
        
        /// <remarks/>
        public string Produto {
            get {
                return this.produtoField;
            }
            set {
                this.produtoField = value;
            }
        }
        
        /// <remarks/>
        public string Resultado {
            get {
                return this.resultadoField;
            }
            set {
                this.resultadoField = value;
            }
        }
        
        /// <remarks/>
        public string corAviso {
            get {
                return this.corAvisoField;
            }
            set {
                this.corAvisoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void retornaLocalEstoqueCompletedEventHandler(object sender, retornaLocalEstoqueCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class retornaLocalEstoqueCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal retornaLocalEstoqueCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public L_LOCALESTOQUE[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((L_LOCALESTOQUE[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void movimentacaoEstoqueCompletedEventHandler(object sender, movimentacaoEstoqueCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class movimentacaoEstoqueCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal movimentacaoEstoqueCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RESULTADOMOV[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RESULTADOMOV[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void recebimentoEstoqueCompletedEventHandler(object sender, recebimentoEstoqueCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class recebimentoEstoqueCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal recebimentoEstoqueCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RESULTADOMOV[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RESULTADOMOV[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void atribuicaoCrachaCompletedEventHandler(object sender, atribuicaoCrachaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class atribuicaoCrachaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal atribuicaoCrachaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RESULTADOMOV[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RESULTADOMOV[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void distribuicaoEPICompletedEventHandler(object sender, distribuicaoEPICompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class distribuicaoEPICompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal distribuicaoEPICompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RESULTADOMOV[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RESULTADOMOV[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void envioParaTesteCompletedEventHandler(object sender, envioParaTesteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class envioParaTesteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal envioParaTesteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RESULTADOMOV[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RESULTADOMOV[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void recebimentoTesteCompletedEventHandler(object sender, recebimentoTesteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class recebimentoTesteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal recebimentoTesteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RESULTADOMOV[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RESULTADOMOV[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void inspecaoEPIFuncionarioCompletedEventHandler(object sender, inspecaoEPIFuncionarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class inspecaoEPIFuncionarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal inspecaoEPIFuncionarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RESULTADOMOV[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RESULTADOMOV[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void itemNaoConformeCompletedEventHandler(object sender, itemNaoConformeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class itemNaoConformeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal itemNaoConformeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RESULTADOMOV[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RESULTADOMOV[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void manutencaoEPICompletedEventHandler(object sender, manutencaoEPICompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class manutencaoEPICompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal manutencaoEPICompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RESULTADOMOV[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RESULTADOMOV[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void funcionarioCrachaCompletedEventHandler(object sender, funcionarioCrachaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class funcionarioCrachaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal funcionarioCrachaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RESULTADOMOV[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RESULTADOMOV[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void FuncionarioTemSenhaCompletedEventHandler(object sender, FuncionarioTemSenhaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FuncionarioTemSenhaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FuncionarioTemSenhaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void cadastrarSenhaCompletedEventHandler(object sender, cadastrarSenhaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cadastrarSenhaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cadastrarSenhaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RESULTADOMOV[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RESULTADOMOV[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void loginFuncionarioCompletedEventHandler(object sender, loginFuncionarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class loginFuncionarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal loginFuncionarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RESULTADOMOV[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RESULTADOMOV[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void devolucaoEPICompletedEventHandler(object sender, devolucaoEPICompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class devolucaoEPICompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal devolucaoEPICompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RESULTADOMOV[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RESULTADOMOV[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void descartarItemCompletedEventHandler(object sender, descartarItemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class descartarItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal descartarItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RESULTADOMOV[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RESULTADOMOV[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void consultaEPICompletedEventHandler(object sender, consultaEPICompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultaEPICompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultaEPICompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RESULTADOMOV[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RESULTADOMOV[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void retornarDadosEpiCompletedEventHandler(object sender, retornarDadosEpiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class retornarDadosEpiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal retornarDadosEpiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RESULTADOMOV[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RESULTADOMOV[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void dateDiffTesteCompletedEventHandler(object sender, dateDiffTesteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class dateDiffTesteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal dateDiffTesteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void importacaoDeDadosCompletedEventHandler(object sender, importacaoDeDadosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class importacaoDeDadosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal importacaoDeDadosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void retornarDadosEpiValidarCompletedEventHandler(object sender, retornarDadosEpiValidarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class retornarDadosEpiValidarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal retornarDadosEpiValidarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DADOSEPI[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DADOSEPI[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void salvarMensagemOcorrenciaCompletedEventHandler(object sender, salvarMensagemOcorrenciaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class salvarMensagemOcorrenciaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal salvarMensagemOcorrenciaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void retornarListaMensagemCompletedEventHandler(object sender, retornarListaMensagemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class retornarListaMensagemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal retornarListaMensagemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RESULTADOMOV[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RESULTADOMOV[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void retornarListaMensagemSupervisorCompletedEventHandler(object sender, retornarListaMensagemSupervisorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class retornarListaMensagemSupervisorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal retornarListaMensagemSupervisorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RESULTADOMOV[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RESULTADOMOV[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void alterarStatusCompletedEventHandler(object sender, alterarStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class alterarStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal alterarStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void dataDifCompletedEventHandler(object sender, dataDifCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class dataDifCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal dataDifCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void retornarDadosEpiValidarRecebimentoCompletedEventHandler(object sender, retornarDadosEpiValidarRecebimentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class retornarDadosEpiValidarRecebimentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal retornarDadosEpiValidarRecebimentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DADOSEPI[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DADOSEPI[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591