//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceIntegracao
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGENDAV
    {
        public int COD_AGE_VEI { get; set; }
        public string COD_PRO { get; set; }
        public Nullable<int> COD_PROF { get; set; }
        public string STATUS { get; set; }
        public Nullable<int> COD_CID { get; set; }
        public Nullable<int> COD_LOC_ATE { get; set; }
        public Nullable<System.DateTime> DATA { get; set; }
        public Nullable<int> COD_VEI_HOR { get; set; }
        public string PASSAGEM { get; set; }
        public string CODLOCAL { get; set; }
        public string ENDLOCAL { get; set; }
        public Nullable<int> COD_UNI { get; set; }
        public string HORA { get; set; }
        public string ACOMPANHANTE { get; set; }
        public string END_ACOMPA { get; set; }
        public string CPF_ACOMPA { get; set; }
        public Nullable<int> NPessoas { get; set; }
        public string RG_ACOMPA { get; set; }
        public Nullable<int> COD_MOT_VIA { get; set; }
        public Nullable<int> COD_COND_TRANS { get; set; }
        public string OBS { get; set; }
        public Nullable<bool> VIAJO { get; set; }
        public string ENDLOCALACOMP { get; set; }
    }
}
