//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceIntegracao
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGENDA_PAC
    {
        public int ID { get; set; }
        public Nullable<int> COD_AGENDA { get; set; }
        public Nullable<System.DateTime> DATA_AGENDAMENTO { get; set; }
        public Nullable<System.DateTime> DATA_CONSULTA { get; set; }
        public string HORA_CONSULTA { get; set; }
        public string COD_PRO { get; set; }
        public string NOME_PAC { get; set; }
        public string PROFISSIONAL { get; set; }
        public Nullable<int> CNES_UNIDADE { get; set; }
        public string UNIDADE { get; set; }
        public string STATUS { get; set; }
        public Nullable<bool> URGENCIA { get; set; }
        public Nullable<System.DateTime> DATA_INSERT { get; set; }
        public Nullable<System.DateTime> DT_ULT_ATUALIZACAO { get; set; }
        public Nullable<System.Guid> CODIGO_QR { get; set; }
        public string CONFIRMADO { get; set; }
        public Nullable<System.DateTime> DATA_CONFIRMACAO { get; set; }
        public Nullable<bool> IMPORTADO_CONFIRMADO { get; set; }
    }
}
