//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceIntegracao
{
    using System;
    using System.Collections.Generic;
    
    public partial class AVALIACAO_TURMA
    {
        public int COD_AVALIACAO { get; set; }
        public Nullable<int> COD_TURMA { get; set; }
        public Nullable<int> COD_DISC { get; set; }
        public Nullable<int> COD_ALUNO { get; set; }
        public Nullable<decimal> BIMESTRE1 { get; set; }
        public string CONCEITO1 { get; set; }
        public Nullable<decimal> BIMESTRE2 { get; set; }
        public string CONCEITO2 { get; set; }
        public Nullable<decimal> BIMESTRE3 { get; set; }
        public string CONCEITO3 { get; set; }
        public Nullable<decimal> BIMESTRE4 { get; set; }
        public string CONCEITO4 { get; set; }
        public Nullable<decimal> MEDIA { get; set; }
        public string MEDIACONCEITO { get; set; }
        public Nullable<decimal> NOTAFINAL { get; set; }
        public Nullable<decimal> NOTACONSELHO { get; set; }
        public Nullable<int> COD_USUARIO { get; set; }
        public Nullable<System.DateTime> DATA { get; set; }
    }
}
