//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceIntegracao
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIDADES
    {
        public int COD_CID { get; set; }
        public string NOME { get; set; }
        public string CEP { get; set; }
        public string CODUF { get; set; }
    }
}
