//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceIntegracao
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISCIPLINAS
    {
        public int COD_DISC { get; set; }
        public Nullable<int> COD_DISCIPLINA_MEC { get; set; }
        public string DISCIPLINA { get; set; }
        public string NOME_DISCIPLINA { get; set; }
        public string ABREVIATURA { get; set; }
        public Nullable<int> COD_DISC_AREA { get; set; }
        public string DESC_FICHA_INDIVIDUAL { get; set; }
    }
}
