//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceIntegracao
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITENS_COM_VALIDADE_DE_TESTE_A_VENCER
    {
        public string Vencer { get; set; }
        public Nullable<System.DateTime> DATA_VENCIMENTO { get; set; }
        public Nullable<int> QTD { get; set; }
        public string VencerHoje { get; set; }
        public Nullable<System.DateTime> DATA_VENCIMENTO_HOJE { get; set; }
        public Nullable<int> QTD_HOJE { get; set; }
        public string Vencer7 { get; set; }
        public Nullable<System.DateTime> DATA_VENCIMENTO_7 { get; set; }
        public Nullable<int> QTD_7 { get; set; }
        public string Vencer15 { get; set; }
        public Nullable<System.DateTime> DATA_VENCIMENTO_15 { get; set; }
        public Nullable<int> QTD_15 { get; set; }
        public string Vencer30 { get; set; }
        public Nullable<System.DateTime> DATA_VENCIMENTO_30 { get; set; }
        public Nullable<int> QTD_30 { get; set; }
    }
}
