//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceIntegracao
{
    using System;
    using System.Collections.Generic;
    
    public partial class L_CLIENTE
    {
        public int ID { get; set; }
        public string NOME { get; set; }
        public string RAZAO_SOCIAL { get; set; }
        public string CNPJ { get; set; }
        public Nullable<int> FK_CLIENTE { get; set; }
        public string GRUPO { get; set; }
        public string CNPJ_GRUPO { get; set; }
    }
}
