//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceIntegracao
{
    using System;
    using System.Collections.Generic;
    
    public partial class L_DESCARTE
    {
        public int ID { get; set; }
        public string LOCAL_ESTOQUE { get; set; }
        public string COD_ESTOQUE { get; set; }
        public string MOTIVO { get; set; }
        public Nullable<int> FK_PRODUTOS_ITENS { get; set; }
        public string EPC { get; set; }
        public Nullable<System.DateTime> DATA_DESCARTE { get; set; }
        public string MATRICULA { get; set; }
    }
}
