//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceIntegracao
{
    using System;
    using System.Collections.Generic;
    
    public partial class L_EPCPERDIDOS
    {
        public string FILIAL { get; set; }
        public string EPC { get; set; }
        public string CODIGO_PRODUTO { get; set; }
        public string LOTE { get; set; }
        public string CODIGO_DE_BARRAS { get; set; }
        public string PRODUTO { get; set; }
        public string ESTOQUE { get; set; }
        public string APURADO { get; set; }
        public string Teve_em_Agosto { get; set; }
        public string Saiu_NF { get; set; }
        public int ID { get; set; }
    }
}
