//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceIntegracao
{
    using System;
    using System.Collections.Generic;
    
    public partial class L_ESTOQUE
    {
        public int ID { get; set; }
        public Nullable<int> FK_PRODUTO { get; set; }
        public string DESC_PRODUTO { get; set; }
        public Nullable<int> QUANTIDADE { get; set; }
        public Nullable<System.DateTime> DATA_ENTRADA { get; set; }
        public string EPC { get; set; }
        public string DATA_SAIDA { get; set; }
        public Nullable<int> FK_FUNCIONARIO_SAIDA { get; set; }
        public string NOME_FUNC_SAIDA { get; set; }
        public Nullable<System.DateTime> ULT_INSPECAO { get; set; }
        public Nullable<System.Guid> COD_RECEBIMENTO { get; set; }
        public string COD_ESTOQUE { get; set; }
        public string ESTOQUE { get; set; }
        public string ENTRADA_SAIDA { get; set; }
        public string COD_PRODUTO { get; set; }
        public string MATRICULA { get; set; }
        public string STATUS { get; set; }
        public string DESC_STATUS { get; set; }
    }
}
