//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceIntegracao
{
    using System;
    using System.Collections.Generic;
    
    public partial class L_FICHACADASTRAL
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> DATA { get; set; }
        public string MATRICULA { get; set; }
        public string FUNCIONARIO { get; set; }
        public string IMPRESSO { get; set; }
    }
}
