//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceIntegracao
{
    using System;
    using System.Collections.Generic;
    
    public partial class L_FUNCAO_PRODUTOS
    {
        public int ID { get; set; }
        public Nullable<int> FK_PRODUTOS { get; set; }
        public string DESC_PRODUTO { get; set; }
        public string DESC_FUNCAO { get; set; }
        public Nullable<int> FK_FUNCAO { get; set; }
    }
}
