//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceIntegracao
{
    using System;
    using System.Collections.Generic;
    
    public partial class L_IMPORTACAO_NOTACLIENTE
    {
        public int ID { get; set; }
        public Nullable<int> NOTA { get; set; }
        public string CNPJ_CLIENTE { get; set; }
        public Nullable<System.DateTime> DATA { get; set; }
        public Nullable<int> QTD_ITENS { get; set; }
        public string NOTIFICACAO { get; set; }
    }
}
