//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceIntegracao
{
    using System;
    using System.Collections.Generic;
    
    public partial class L_INSPITEM
    {
        public int ID { get; set; }
        public Nullable<int> FK_INSPECAO { get; set; }
        public string EPC { get; set; }
        public string COD_PRODUTO { get; set; }
        public string DESC_PRODUTO { get; set; }
        public string FORNECEDOR { get; set; }
        public string CA { get; set; }
        public Nullable<System.DateTime> DATA_FABRICACAO { get; set; }
        public Nullable<System.DateTime> DATA_VALIDADE { get; set; }
        public Nullable<System.DateTime> DATA_VALIDADE_TESTE { get; set; }
        public string LOTE { get; set; }
        public string SITUACAO { get; set; }
        public string COD_FORNECEDOR { get; set; }
        public string COD_SITUACAO { get; set; }
    }
}
