//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceIntegracao
{
    using System;
    using System.Collections.Generic;
    
    public partial class L_LOGIN_FUNCIONARIO
    {
        public int ID { get; set; }
        public Nullable<int> FK_FUNCIONARIO { get; set; }
        public string DESC_FUNCIONARIO { get; set; }
        public string CRACHA { get; set; }
        public string SENHA { get; set; }
        public string MATRICULA { get; set; }
    }
}
