//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceIntegracao
{
    using System;
    using System.Collections.Generic;
    
    public partial class L_MENSAGEM_OCORRENCIA
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> DATA_MENSAGEM { get; set; }
        public string NUMERO { get; set; }
        public string MENSAGEM { get; set; }
        public string OCORRENCIA { get; set; }
    }
}
