//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceIntegracao
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_HISTORICOATENDIMENTO
    {
        public int ID_HISTORICOATENDIMENTO { get; set; }
        public Nullable<System.DateTime> DATA { get; set; }
        public Nullable<System.TimeSpan> HORA { get; set; }
        public string DESCRICAO { get; set; }
        public Nullable<int> ID_OCORRENCIA { get; set; }
        public Nullable<int> ID_USUARIO { get; set; }
        public Nullable<int> STATUS_MENSAGEM { get; set; }
        public string DESC_STATUS { get; set; }
    }
}
