//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceIntegracao
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_OCORRENCIA
    {
        public int ID_OCORRENCIA { get; set; }
        public string DESCRICAO { get; set; }
        public int ID_STATUSOCORRENCIA { get; set; }
        public int ID_USUARIO { get; set; }
        public string CEP { get; set; }
        public string ENDERECO { get; set; }
        public string NUMERO { get; set; }
        public string COMPLEMENTO { get; set; }
        public string BAIRRO { get; set; }
        public string CIDADE { get; set; }
        public string UF { get; set; }
        public string LONGITUDE { get; set; }
        public string LATITUDE { get; set; }
        public string ID_PRODUTO { get; set; }
        public Nullable<int> ID_MENSAGEM_OCORRENCIA { get; set; }
        public Nullable<System.DateTime> DATA { get; set; }
    }
}
