//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceIntegracao
{
    using System;
    using System.Collections.Generic;
    
    public partial class PACIENTES
    {
        public string COD_PRO { get; set; }
        public Nullable<int> COD_CIDADAO { get; set; }
        public string NOME { get; set; }
        public Nullable<System.DateTime> DTMATRIC { get; set; }
        public Nullable<System.DateTime> DTMORADIA { get; set; }
        public string OBS { get; set; }
        public string OBS_ESC { get; set; }
        public string RH { get; set; }
        public string GRUPO { get; set; }
        public Nullable<int> CONSULTAOK { get; set; }
        public Nullable<int> CONSULTANOK { get; set; }
        public Nullable<System.DateTime> UCONSULTA { get; set; }
        public string RESPONSAVEL { get; set; }
        public Nullable<float> PESONASC { get; set; }
        public Nullable<float> ALTURANASC { get; set; }
        public string HORANASC { get; set; }
        public string OBSNASC { get; set; }
        public string TIPO_PARTO { get; set; }
        public Nullable<float> PERIMETRO { get; set; }
        public string APGAR { get; set; }
        public string SOCIAL { get; set; }
        public string HISTORICO { get; set; }
        public string ALTERADO { get; set; }
        public string NUMSPROT { get; set; }
        public string ANTIGO { get; set; }
        public Nullable<int> UNI_ULTCONSULTA { get; set; }
        public Nullable<int> ULT_PROF { get; set; }
        public string DOADORSANGUE { get; set; }
        public Nullable<System.DateTime> DT_ULTALT { get; set; }
        public string COD_ODONTO { get; set; }
        public string QUADRA { get; set; }
        public string CONVENIO { get; set; }
        public string TIPO_PLANO { get; set; }
        public string LOC_PRONTUARIO { get; set; }
        public Nullable<bool> ATIVO { get; set; }
        public Nullable<int> NIMPETIQTERMICA { get; set; }
        public Nullable<bool> HIPERTENSO { get; set; }
        public Nullable<bool> DIABETICO { get; set; }
        public Nullable<int> COD_UNIORIGEM { get; set; }
        public string UNIDADE_ORIGEM { get; set; }
        public Nullable<int> COD_AME { get; set; }
        public string APGAR1 { get; set; }
        public Nullable<bool> TEM_FICHA_GERADA { get; set; }
        public Nullable<bool> CANCER { get; set; }
        public Nullable<bool> PNEUMOPATIA { get; set; }
        public Nullable<bool> TRANSPLANTADO { get; set; }
        public Nullable<bool> ALERGIA { get; set; }
        public Nullable<bool> OUTRAS_COMORBIDADES { get; set; }
        public string ANTECED_PESSOAL { get; set; }
        public Nullable<System.DateTime> DATA_INSERT { get; set; }
        public Nullable<System.DateTime> DT_ULT_ATUALIZACAO { get; set; }
        public Nullable<System.Guid> CODIGO_QR { get; set; }
    }
}
