//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceIntegracao
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROFISSIONAIS
    {
        public int COD_PROF { get; set; }
        public Nullable<System.DateTime> DTCAD { get; set; }
        public string NOME { get; set; }
        public string SEXO { get; set; }
        public string ENDERECO { get; set; }
        public string BAIRRO { get; set; }
        public string MUNICIPIO { get; set; }
        public string CEP { get; set; }
        public string NLICENCA { get; set; }
        public string CPF { get; set; }
        public string RG { get; set; }
        public Nullable<System.DateTime> DTNASC { get; set; }
        public string DDD { get; set; }
        public string FONERES { get; set; }
        public string FONECOM { get; set; }
        public string CELULAR { get; set; }
        public Nullable<int> COD_PFS { get; set; }
        public string ATIVO { get; set; }
        public string CONJUGUE { get; set; }
        public Nullable<System.DateTime> NASCCONJUGUE { get; set; }
        public string NUM { get; set; }
        public Nullable<int> COD_AREA { get; set; }
        public Nullable<int> COD_MICRO { get; set; }
        public string CNS { get; set; }
        public string NOMEUSUARIO { get; set; }
        public Nullable<int> COD_LOGRADOURO { get; set; }
        public Nullable<int> COD_TIPOLOG { get; set; }
        public string CODUF { get; set; }
        public Nullable<int> COD_CIDADAO { get; set; }
        public string TITULO { get; set; }
        public Nullable<bool> ATIVA_PAINEL_SENHA { get; set; }
    }
}
