//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceIntegracao
{
    using System;
    using System.Collections.Generic;
    
    public partial class QTD_INCONFORMIDADE_EMAIL
    {
        public Nullable<int> DIA0 { get; set; }
        public string DIA0LINK { get; set; }
        public string DIA0TEXT { get; set; }
        public Nullable<int> DIA1 { get; set; }
        public string DIA1LINK { get; set; }
        public string DIA1TEXT { get; set; }
        public Nullable<int> DIA2 { get; set; }
        public string DIA2LINK { get; set; }
        public string DIA2TEXT { get; set; }
        public Nullable<int> DIA3 { get; set; }
        public string DIA3LINK { get; set; }
        public string DIA3TEXT { get; set; }
        public Nullable<int> DIA4 { get; set; }
        public string DIA4LINK { get; set; }
        public string DIA4TEXT { get; set; }
        public Nullable<int> DIA5 { get; set; }
        public string DIA5LINK { get; set; }
        public string DIA5TEXT { get; set; }
        public Nullable<int> DIA6 { get; set; }
        public string DIA6LINK { get; set; }
        public string DIA6TEXT { get; set; }
        public Nullable<int> DIA7 { get; set; }
        public string DIA7LINK { get; set; }
        public string DIA7TEXT { get; set; }
        public Nullable<int> DIA15 { get; set; }
        public string DIA15LINK { get; set; }
        public string DIA15TEXT { get; set; }
        public Nullable<int> DIA30 { get; set; }
        public string DIA30LINK { get; set; }
        public string DIA30TEXT { get; set; }
    }
}
