//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceIntegracao
{
    using System;
    using System.Collections.Generic;
    
    public partial class RELACAO_NUMERICA
    {
        public Nullable<double> COD { get; set; }
        public string CARGO { get; set; }
        public string SIGLA { get; set; }
        public string NOME { get; set; }
        public string TELEFONE { get; set; }
        public string EMAIL { get; set; }
        public Nullable<System.DateTime> DATA_NASC { get; set; }
        public string SECRETARIA { get; set; }
        public Nullable<int> FK_CARGO { get; set; }
        public Nullable<int> FK_CARGO_SEC { get; set; }
        public int ID { get; set; }
        public byte[] FOTO { get; set; }
    }
}
