//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceIntegracao
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tab_Login
    {
        public int cd_usuario { get; set; }
        public string st_nome_usuario { get; set; }
        public string st_email_usuario { get; set; }
        public string st_login_usuario { get; set; }
        public string st_senha_usuario { get; set; }
        public int cd_tipo_usuario { get; set; }
        public Nullable<float> vl_ajuda_custo { get; set; }
        public Nullable<int> fl_ativo_usuario { get; set; }
        public Nullable<System.DateTime> dt_criacao_usuario { get; set; }
        public Nullable<System.DateTime> dt_saida_usuario { get; set; }
        public string st_endereco { get; set; }
        public string st_cidade { get; set; }
        public string st_cep { get; set; }
        public string st_tel_residencial { get; set; }
        public string st_tel_celular { get; set; }
        public string st_rg_usuario { get; set; }
        public string st_cpf_usuario { get; set; }
        public string st_obs_usuario { get; set; }
        public string st_personal { get; set; }
        public Nullable<System.DateTime> dt_nascimento { get; set; }
        public string fl_Sexo { get; set; }
        public Nullable<System.DateTime> dt_atualizacao { get; set; }
        public string fl_novo_usuario { get; set; }
        public string abrir_enquete { get; set; }
    }
}
