//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceIntegracao
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSPORTE_PAC
    {
        public int ID { get; set; }
        public Nullable<int> COD_AGE_VIA { get; set; }
        public Nullable<int> CNES_UNIDADE { get; set; }
        public string UNIDADE { get; set; }
        public Nullable<System.DateTime> DATA_VIAGEM { get; set; }
        public string HORA_SAIDA { get; set; }
        public string LOCAL_EMBARQUE { get; set; }
        public string ACOMPANHANTE { get; set; }
        public string LOCAL_EMBARQUE_ACOMP { get; set; }
        public string STATUS { get; set; }
        public string VEICULO { get; set; }
        public string CIDADE_ATENDIMENTO { get; set; }
        public string LOCAL_ATENDIMENTO { get; set; }
        public string END_ATENDIMENTO { get; set; }
        public string HORA_ATENDIMENTO { get; set; }
        public string COD_PRO { get; set; }
        public string NOME_PAC { get; set; }
        public string MOTORISTA { get; set; }
        public Nullable<System.DateTime> DATA_INSERT { get; set; }
        public Nullable<System.DateTime> DT_ULT_ATUALIZACAO { get; set; }
        public Nullable<System.Guid> CODIGO_QR { get; set; }
        public Nullable<bool> IMPORTADO_STATUS { get; set; }
    }
}
