//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceIntegracao
{
    using System;
    using System.Collections.Generic;
    
    public partial class TURMAS
    {
        public int COD_TURMA { get; set; }
        public Nullable<int> COD_ESCOLA { get; set; }
        public string TURMA { get; set; }
        public Nullable<int> COD_CURSO { get; set; }
        public Nullable<int> COD_TURNO { get; set; }
        public Nullable<int> COD_CURRICULO { get; set; }
        public Nullable<int> COD_SERIE { get; set; }
        public Nullable<int> COD_DEPENDENCIA { get; set; }
        public Nullable<int> COD_AVALIACAO { get; set; }
        public string NOMETURMA { get; set; }
        public Nullable<System.DateTime> DATA_CRIACAO { get; set; }
        public Nullable<System.DateTime> DATA_ULT_ATUALIZACAO { get; set; }
        public Nullable<int> MAXIMOALUNOS { get; set; }
        public Nullable<int> MINIMODIASLETIVOS { get; set; }
        public Nullable<System.DateTime> DATA_FECHAMENTO { get; set; }
        public Nullable<int> NUMEROALUNOSMATRICULADOS { get; set; }
        public Nullable<int> DIASLETIVOS { get; set; }
        public string ANOLETIVO { get; set; }
        public string PERIODOLETIVO { get; set; }
        public string TURMA_FECHADA { get; set; }
        public string STATUS { get; set; }
        public Nullable<int> COD_USUARIO { get; set; }
    }
}
