//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceIntegracao
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public int pk { get; set; }
        public string nome { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> data_ativacao { get; set; }
        public string menus { get; set; }
    }
}
