//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceIntegracao
{
    using System;
    using System.Collections.Generic;
    
    public partial class VACINA
    {
        public int COD_VACI { get; set; }
        public string NOME { get; set; }
        public string ESPECIFICACAO { get; set; }
        public string CONTRA_IND { get; set; }
        public string EVENTOS_AD { get; set; }
        public string EFICACIA { get; set; }
        public Nullable<int> VALIDADE { get; set; }
        public string VALIDADE_HDMA { get; set; }
        public Nullable<int> NDOSES_BASICA { get; set; }
        public string DESCRI_DOSE_BASICA { get; set; }
        public Nullable<int> INICIO_VACI { get; set; }
        public string INICIO_VACI_DMA { get; set; }
        public Nullable<int> INTERV_REC { get; set; }
        public string INTERV_REC_DMA { get; set; }
        public Nullable<int> INTERV_MIN { get; set; }
        public string INTERV_MIN_DMA { get; set; }
        public string TEMP_NAC_MIN { get; set; }
        public string TEMP_NAC_MAX { get; set; }
        public string TEMP_EST_MIN { get; set; }
        public string TEMP_EST_MAX { get; set; }
        public string TEMP_LOC_MIN { get; set; }
        public string TEMP_LOC_MAX { get; set; }
        public Nullable<int> COD_COMP_VAC { get; set; }
        public Nullable<int> REFORCO { get; set; }
        public string REFORCO_DMA { get; set; }
        public Nullable<bool> CARTEIRA { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public Nullable<int> COD_UNI_MED { get; set; }
        public Nullable<decimal> VOLUME_DOSE { get; set; }
        public Nullable<int> INTERV_REC2 { get; set; }
        public string INTERV_REC2_DMA { get; set; }
        public Nullable<int> INTERV_REC3 { get; set; }
        public string INTERV_REC3_DMA { get; set; }
        public string TIPO_REFORCO { get; set; }
        public Nullable<int> REFORCO2 { get; set; }
        public string REFORCO2_DMA { get; set; }
    }
}
