//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceIntegracao
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEICULOS
    {
        public int COD_VEI { get; set; }
        public string DESCRICAO { get; set; }
        public string PLACA { get; set; }
        public string OBS { get; set; }
        public Nullable<float> CAPACIDADE { get; set; }
        public Nullable<int> COD_PROF { get; set; }
        public string MARCA { get; set; }
        public string KMINI { get; set; }
        public string CHASSIS { get; set; }
        public string ANOFAB { get; set; }
        public string ANOMOD { get; set; }
        public string SETOR { get; set; }
        public Nullable<System.DateTime> DTVENCIMENTODOC { get; set; }
        public Nullable<int> CODIGO_CONDICAOTRANSPORTE { get; set; }
    }
}
